FROM ubuntu:24.04

# Avoid interactive prompts during apt operations
ENV DEBIAN_FRONTEND=noninteractive

# Install essential tools required for the bootstrapper to function
RUN apt-get update && apt-get install -y \
    sudo \
    bash \
    curl \
    git \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash user && \
    echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# RUN --mount=type=secret,id=github_token \
#     GITHUB_TOKEN=$(cat /run/secrets/github_token) && \
#     curl -H "Authorization: Bearer $GITHUB_TOKEN" \
#         -H "Accept: application/vnd.github.v3.raw" \
#         -fsSL "https://api.github.com/repos/yveskaufmann/dotfiles-cli/contents/scripts/install.sh?ref=main" | sh

RUN echo "1"
COPY scripts/install.sh /tmp/install.sh
RUN --mount=type=secret,id=github_token \
    sudo sh /tmp/install.sh --github-token "$(cat /run/secrets/github_token)"

USER user
WORKDIR /home/user/

ENTRYPOINT ["/bin/bash"]
